<?php
//
// ZoneMinder network address helpers
//
// Kept dependency-free so that the IP-bound auth hash (ZM_AUTH_HASH_IPS) uses
// identical logic on the generation side (session.php) and the validation side
// (auth.php), and so the behaviour can be unit tested standalone. The C++
// daemons (zms/zmu) have a byte-for-byte equivalent in zm_utils AuthNetworkPrefix.
//

// Return the effective client address: the first hop of X-Forwarded-For when
// present (reverse-proxy setups), otherwise REMOTE_ADDR. Only the first value is
// used to avoid trusting spoofed multi-value headers.
function getRemoteAddr() {
  if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    return trim(explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'])[0]);
  }
  return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '';
}

// Reduce an IP address to its network prefix so an auth hash survives a client
// changing host address within the same network: IPv4 is masked to /24, IPv6 to
// /64. IPv6 privacy/temporary addresses (RFC 4941) and many carrier NAT pools
// keep the same prefix while the host portion rotates, which was causing
// AUTH_HASH_IPS to bounce users back to the login page.
//
// Returns a lowercase hex string of the masked address bytes. The exact text is
// unimportant on its own; what matters is that it is deterministic and identical
// to the C++ AuthNetworkPrefix so a hash generated by one side validates on the
// other. Empty or non-IP input is returned unchanged.
function authNetworkPrefix($ip) {
  if ($ip === '' or $ip === null) {
    return '';
  }
  $packed = @inet_pton($ip);
  if ($packed === false) {
    return $ip; // not an IP address, hash it verbatim
  }
  $len = strlen($packed);
  if ($len == 4) {          // IPv4 -> /24, zero the last octet
    $masked = substr($packed, 0, 3)."\0";
  } else if ($len == 16) {  // IPv6 -> /64, zero the low 64 bits
    $masked = substr($packed, 0, 8).str_repeat("\0", 8);
  } else {
    return $ip;
  }
  return bin2hex($masked);
}
?>
