
package WSDiscovery::Elements::Types;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01' }

__PACKAGE__->__set_name('Types');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    WSDiscovery::Types::QNameListType
);

}

1;


=pod

=head1 NAME

WSDiscovery::Elements::Types

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
Types from the namespace http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01.







=head1 METHODS

=head2 new

 my $element = WSDiscovery::Elements::Types->new($data);

Constructor. The following data structure may be passed to new():

$some_value, # QNameListType

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

