language: cpp
notifications:
  irc: chat.freenode.net#zoneminder-dev
branches:
  except:
  - modern
env:
  global:
  - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
  - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
  - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
  - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
  - CXXFLAGS="$CFLAGS"
  - SAUCE_BROWSER=firefox
  - secure: SFHK8N7eZT6rYgDqQb20b7KGi41xALie3uNp1tqCLHrJ15tK//6XivsCQQ7ocJIowNrHg5Ih5YBlu1cLuULrB4uxINxZf6ussXta4ik29wgQOw8UJxoF0wkOV4ZNoU7TWpKAtHOaK7uMXw44RMqBNsJI/WEydvV0vqBvikqi1P4=
  - secure: ubV7HS75AlG8ZgGFA9YVTc2lrguL5RBWPuhUccc6qSkg/vrfufwfmicrELmpURH9Hep/UM13tf05V0CidUUwEv6CB9EJx2+h7n4imM3kmvC3/LO/TH2A49p87Qvw0CnOP3qFjIu5f0XQDxuMACFiX9LnH+IqMuRyIbeqK3FuduU=
  matrix:
  - ZM_BUILDMETHOD=cmake
  - ZM_BUILDMETHOD=autotools
addons:
  sauce_connect: 
compiler:
- gcc
before_install: 
install:
- travis_retry bash $TRAVIS_BUILD_DIR/utils/travis/install-deps.sh
- travis_wait bash $TRAVIS_BUILD_DIR/utils/travis/install-ffmpeg.sh
- bash $TRAVIS_BUILD_DIR/utils/travis/bootstrap-zm.sh
- bash $TRAVIS_BUILD_DIR/utils/travis/build-zm.sh
before_script: 
script:
- bash $TRAVIS_BUILD_DIR/utils/travis/run-tests.sh
