language: cpp
notifications:
  irc: "chat.freenode.net#zoneminder-dev"
branches:
  except:
    - modern
env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
    - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
    - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
    - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
    - CXXFLAGS="$CFLAGS"
    - secure: iSnKALpWDY3I1vr+Iv/BkhAW8WHUiIl06Aw6sPeEGHNMqWamgx5aQJquoplg5q+RckDfIeZ3yGAr/PnLhRWoWazgcXZN+pB5frIP7eb0m7CGX/QUybIDVJ0eKCqAK5aR2jV59NVDGeKQfm7E6PVGJuuAwVMsujirtsmaGTGrmGo=
    - secure: Dt9a4rqYwSawuzYOcEYHCYSfh8XykiUZdUW/KhlJWjxpaWEl20XdcB7CXlSpM2w45Fp2+lXG1U61xRp5cjy/oPspELSTpGDm/5Ql0r1vf+ReelvoT4fD2YRECvLTmDb+ieHu3CULUZ5f1MItJ2kfwbV7BIsKrsKl1G7ORb61VNY=
    - SAUCE_BROWSER=firefox
  matrix:
    - ZM_BUILDMETHOD=cmake
    - ZM_BUILDMETHOD=autotools
addons:
  sauce_connect:
compiler:
  - gcc
before_install:
install:
  - travis_retry bash $TRAVIS_BUILD_DIR/utils/travis/install-deps.sh
  - travis_wait bash $TRAVIS_BUILD_DIR/utils/travis/install-ffmpeg.sh
  - bash $TRAVIS_BUILD_DIR/utils/travis/bootstrap-zm.sh
  - bash $TRAVIS_BUILD_DIR/utils/travis/build-zm.sh
before_script:
script:
  - bash $TRAVIS_BUILD_DIR/utils/travis/run-tests.sh
