language: cpp
notifications:
  irc: chat.freenode.net#zoneminder-dev
branches:
  except:
  - modern
env:
  global:
  - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
  - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
  - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
  - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
  - CXXFLAGS="$CFLAGS"
  - secure: SxZuhYAnYpwMnitptHGkR6ioiXVaXggV7fNJNUD1pkcX+jfeMM3KxyLALTFp5d0nqxZxASXQRqbcuhjFO1osUednnNkWWBJaeZX+Ww97tnVj3tcqaJuDYEZrmkMuFwfiNWD1nkLl2B6hu79juaY74ch1pvO/B2juIakVw6kyQHc=
  - secure: c5WUnTdlucNE+CVoeyzjVscG1uV1kM5f9FpYdxnBp95l4ilE7eWXQ1EbEUlInJpTqXMKBfsJzhiM1aGavV5yJ5D+1vKzDQ+Ec2KaO2tG0V9QB9Jt5abfll4UTdq7EIhAIYQOm3onNeRyxfbQPx2PWe2SMKE1f26n8bpUIhJz5xc=

  matrix:
  - ZM_BUILDMETHOD=cmake
  - ZM_BUILDMETHOD=autotools
addons:
  sauce_connect: 
compiler:
- gcc
before_install: 
install:
- travis_retry bash $TRAVIS_BUILD_DIR/utils/travis/install-deps.sh
- travis_wait bash $TRAVIS_BUILD_DIR/utils/travis/install-ffmpeg.sh
before_script:
- bash $TRAVIS_BUILD_DIR/utils/travis/bootstrap-zm.sh
script:
- bash $TRAVIS_BUILD_DIR/utils/travis/build-zm.sh
after_script:
- bash $TRAVIS_BUILD_DIR/utils/travis/run-tests.sh
