language: cpp
notifications:
  irc: "chat.freenode.net#zoneminder-dev"
branches:
  except:
    - modern
env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
    - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
    - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
    - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
    - CXXFLAGS="$CFLAGS"
    - secure: fzfeQe67f4wYkszMtEoHwkXLDoNfeu1xzPON6e9hojzgnc3Py4BtQSy9qohaN4neLsxs8nwXOxlTDjY8vaGZfTpfAwpeupdgp5ZZW0ok1caEFdp/qKdJveW7FP2KQUkSezhXdmjBGMotquQooTZiZlCR9aGkA5bBeZGNYsI+o4A=
    - secure: FuO4X2qf/fX5Fp/FRG6Z2s6f10ngsXt/yCgCLUeDD2DDeYHEgXQarbi4eoPv9XzjUvNKDNdnGCV2SjLsDB6EaoK4GmMnqN9lBmi7tP1QYeNBt27V7BfiB6vIxJApkynAwOpDVLoM4wCv7uIsSfSMKL1czfXXtv9iuSi7Y5840RQ=
    - SAUCE_BROWSER=firefox
matrix:
  - ZM_BUILDMETHOD=cmake
  - ZM_BUILDMETHOD=autotools
addons:
  sauce_connect:
compiler:
  - gcc
before_install:
install:
  - travis_retry bash $TRAVIS_BUILD_DIR/utils/travis/install-deps.sh
  - travis_wait bash $TRAVIS_BUILD_DIR/utils/travis/install-ffmpeg.sh
  - bash $TRAVIS_BUILD_DIR/utils/travis/bootstrap-zm.sh
  - bash $TRAVIS_BUILD_DIR/utils/travis/build-zm.sh
before_script:
script:
  - bash $TRAVIS_BUILD_DIR/utils/travis/run-tests.sh
