language: cpp
notifications:
  irc: "chat.freenode.net#zoneminder-dev"
branches:
  except:
    - modern
env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
    - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
    - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
    - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
    - CXXFLAGS="$CFLAGS"
  matrix:
    - ZM_BUILDMETHOD=cmake
    - ZM_BUILDMETHOD=autotools
compiler:
  - gcc
before_install:
install:
  - travis_retry bash $TRAVIS_BUILD_DIR/utils/travis/install-deps.sh
  - travis_wait bash $TRAVIS_BUILD_DIR/utils/travis/install-ffmpeg.sh
before_script:
  - bash $TRAVIS_BUILD_DIR/utils/travis/bootstrap-zm.sh
script:
  - bash $TRAVIS_BUILD_DIR/utils/travis/build-zm.sh
  - bash $TRAVIS_BUILD_DIR/utils/travis/run-tests.sh
