language: cpp
sudo: required
dist: trusty

notifications:
  irc: "chat.freenode.net#zoneminder-dev"

branches:
  except:
    - modern

cache: ccache

addons:
  sauce_connect:
    username: "zoneminder"
    access_key: "046ec7c1-c598-4e7e-949a-f86e725d1722"

env:
  matrix:
    - OS=el DIST=6
    - OS=el DIST=7
    - OS=fedora DIST=24
    - OS=fedora DIST=25
#    - OS=ubuntu DIST=trusty
#    - OS=ubuntu DIST=precise
#    - OS=ubuntu DIST=xenial
#    - OS=ubuntu DIST=yakkety
#    - OS=debian DIST=jessie
#    - OS=debian DIST=wheezy
#    - OS=debian DIST=stretch

compiler:
  - gcc
  - clang
services:
  - docker
script:
  - ln -s ./distros/redhat ./rpm
  - git submodule update --init --recursive
  - git describe --long
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack

deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    branch: master
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

