language: 
    - cpp
    - C
sudo: required
dist: trusty
notifications:
  irc: "chat.freenode.net#zoneminder-dev"
branches:
  except:
    - modern
cache: 
     - ccache
    directories:
     - $HOME/.cache

addons:
  sauce_connect:
    username: "zoneminder"
    access_key: "046ec7c1-c598-4e7e-949a-f86e725d1722"
env:
  global:
    - LD_LIBRARY_PATH="/usr/local/lib:/opt/libjpeg-turbo/lib:$LD_LIBRARY_PATH"
    - DEB_HOST_GNU_TYPE=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
    - DEB_BUILD_GNU_TYPE=$(dpkg-architecture -qDEB_BUILD_GNU_TYPE)
    - CFLAGS="-DZM_FFMPEG_CVS -DHAVE_LIBCRYPTO -I/usr/local/include"
    - CXXFLAGS="$CFLAGS"
  matrix:
    - ZM_BUILDMETHOD=cmake
    - OS=el DIST=6
    - OS=el DIST=7
    - OS=fedora DIST=23
    - OS=fedora DIST=24
    - OS=fedora DIST=25
    - OS=ubuntu DIST=trusty
    - OS=ubuntu DIST=precise
    - OS=ubuntu DIST=xenial
    - OS=ubuntu DIST=yakkety
    - OS=debian DIST=jessie
    - OS=debian DIST=wheezy
    - OS=debian DIST=stretch

compiler:
  - gcc
  - clang
services:
  - mysql
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpolkit-gobject-1-dev zlib1g-dev apache2 php5 php5-mysql build-essential libmysqlclient-dev libssl-dev libbz2-dev libpcre3-dev libdbi-perl libarchive-zip-perl libdate-manip-perl libdevice-serialport-perl libmime-perl libwww-perl libdbd-mysql-perl libsys-mmap-perl yasm automake autoconf cmake libjpeg-turbo8-dev apache2-mpm-prefork libapache2-mod-php5 php5-cli libtheora-dev libvorbis-dev libvpx-dev libx264-dev libvlccore-dev libvlc-dev
install:
  - git clone -b n3.0 --depth=1 git://source.ffmpeg.org/ffmpeg.git
  - cd ffmpeg
  - ./configure --enable-shared --enable-swscale --enable-gpl  --enable-libx264 --enable-libvpx --enable-libvorbis --enable-libtheora 
  - make -j `grep processor /proc/cpuinfo|wc -l` 
  - sudo make install 
  - sudo make install-libs
before_script:
  - cd $TRAVIS_BUILD_DIR
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS zm"
  - mysql -uroot -e "GRANT ALL ON zm.* TO 'zmuser'@'localhost' IDENTIFIED BY 'zmpass'";
  - mysql -uroot -e "FLUSH PRIVILEGES"
script:
  - if [ "$ZM_BUILDMETHOD" = "cmake" ]; then cmake -DZM_ONVIF=OFF -DCMAKE_INSTALL_PREFIX="/usr"; fi
  - make
  - sudo make install
  - if [ "$ZM_BUILDMETHOD" = "cmake" ]; then sudo ./zmlinkcontent.sh; fi
  - mysql -uzmuser -pzmpass < db/zm_create.sql
  - mysql -uzmuser -pzmpass zm < db/test.monitor.sql
  - sudo zmpkg.pl start
  - sudo zmfilter.pl -f purgewhenfull

after_success:
  - git submodule update --init --recursive
  - git describe --long
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack

deploy:
  # Deploy packages to PackageCloud
  provider: packagecloud
  username: ${PACKAGECLOUD_USER}
  repository: ${PACKAGECLOUD_REPO}
  token: ${PACKAGECLOUD_TOKEN}
  dist: ${OS}/${DIST}
  package_glob: build/*.{deb,rpm}
  skip_cleanup: true
  on:
    branch: master
    condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

