
package ONVIF::Media::Elements::GetAudioSourcesResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/media/wsdl' }

__PACKAGE__->__set_name('GetAudioSourcesResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AudioSources_of :ATTR(:get<AudioSources>);

__PACKAGE__->_factory(
    [ qw(        AudioSources

    ) ],
    {
        'AudioSources' => \%AudioSources_of,
    },
    {
        'AudioSources' => 'ONVIF::Media::Types::AudioSource',
    },
    {

        'AudioSources' => 'AudioSources',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Media::Elements::GetAudioSourcesResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetAudioSourcesResponse from the namespace http://www.onvif.org/ver10/media/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * AudioSources

 $element->set_AudioSources($data);
 $element->get_AudioSources();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Media::Elements::GetAudioSourcesResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   AudioSources =>  { # ONVIF::Media::Types::AudioSource
     Channels =>  $some_value, # int
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

