
package ONVIF::Media::Elements::GetStreamUriResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/media/wsdl' }

__PACKAGE__->__set_name('GetStreamUriResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %MediaUri_of :ATTR(:get<MediaUri>);

__PACKAGE__->_factory(
    [ qw(        MediaUri

    ) ],
    {
        'MediaUri' => \%MediaUri_of,
    },
    {
        'MediaUri' => 'ONVIF::Media::Types::MediaUri',
    },
    {

        'MediaUri' => 'MediaUri',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Media::Elements::GetStreamUriResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetStreamUriResponse from the namespace http://www.onvif.org/ver10/media/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * MediaUri

 $element->set_MediaUri($data);
 $element->get_MediaUri();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Media::Elements::GetStreamUriResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   MediaUri =>  { # ONVIF::Media::Types::MediaUri
     Uri =>  $some_value, # anyURI
     InvalidAfterConnect =>  $some_value, # boolean
     InvalidAfterReboot =>  $some_value, # boolean
     Timeout =>  $some_value, # duration
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

