
package ONVIF::Media::Elements::Polyline;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/schema' }

__PACKAGE__->__set_name('Polyline');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    ONVIF::Media::Types::Polyline
);

}

1;


=pod

=head1 NAME

ONVIF::Media::Elements::Polyline

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
Polyline from the namespace http://www.onvif.org/ver10/schema.







=head1 METHODS

=head2 new

 my $element = ONVIF::Media::Elements::Polyline->new($data);

Constructor. The following data structure may be passed to new():

 { # ONVIF::Media::Types::Polyline
   Point => ,
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

