
package ONVIF::Media::Elements::SetVideoSourceModeResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/media/wsdl' }

__PACKAGE__->__set_name('SetVideoSourceModeResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Reboot_of :ATTR(:get<Reboot>);

__PACKAGE__->_factory(
    [ qw(        Reboot

    ) ],
    {
        'Reboot' => \%Reboot_of,
    },
    {
        'Reboot' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    },
    {

        'Reboot' => 'Reboot',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Media::Elements::SetVideoSourceModeResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SetVideoSourceModeResponse from the namespace http://www.onvif.org/ver10/media/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Reboot

 $element->set_Reboot($data);
 $element->get_Reboot();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Media::Elements::SetVideoSourceModeResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   Reboot =>  $some_value, # boolean
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

