#! /bin/sh
set -e

if [ "$1" = "purge" ]; then
    if [ -e "/etc/init.d/mysql" ]; then 
        echo 'delete from user where User="zmuser";' | mysql --defaults-file=/etc/mysql/debian.cnf mysql
        echo 'delete from db where User="zmuser";' | mysql --defaults-file=/etc/mysql/debian.cnf mysql
        mysqladmin --defaults-file=/etc/mysql/debian.cnf -f drop zm
    fi
fi
#DEBHELPER#
