package ONVIF::Media::Types::ProfileCapabilities;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/media/wsdl' };

our $XML_ATTRIBUTE_CLASS = 'ONVIF::Media::Types::ProfileCapabilities::_ProfileCapabilities::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables


__PACKAGE__->_factory(
    [ qw(
    ) ],
    {
    },
    {
    },
    {

    }
);

} # end BLOCK




package ONVIF::Media::Types::ProfileCapabilities::_ProfileCapabilities::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %MaximumNumberOfProfiles_of :ATTR(:get<MaximumNumberOfProfiles>);

__PACKAGE__->_factory(
    [ qw(
        MaximumNumberOfProfiles
    ) ],
    {

        MaximumNumberOfProfiles => \%MaximumNumberOfProfiles_of,
    },
    {
        MaximumNumberOfProfiles => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
    }
);

} # end BLOCK




1;


=pod

=head1 NAME

ONVIF::Media::Types::ProfileCapabilities

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ProfileCapabilities from the namespace http://www.onvif.org/ver10/media/wsdl.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Media::Types::ProfileCapabilities
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class ONVIF::Media::Types::ProfileCapabilities::_ProfileCapabilities::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * MaximumNumberOfProfiles

 Maximum number of profiles supported.



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::int|SOAP::WSDL::XSD::Typelib::Builtin::int>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

