package ONVIF::Media::Types::PTZFilter;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Status_of :ATTR(:get<Status>);
my %Position_of :ATTR(:get<Position>);

__PACKAGE__->_factory(
    [ qw(        Status
        Position

    ) ],
    {
        'Status' => \%Status_of,
        'Position' => \%Position_of,
    },
    {
        'Status' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
        'Position' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    },
    {

        'Status' => 'Status',
        'Position' => 'Position',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::Media::Types::PTZFilter

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
PTZFilter from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Status


=item * Position




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Media::Types::PTZFilter
   Status =>  $some_value, # boolean
   Position =>  $some_value, # boolean
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

