
package WSDiscovery10::Elements::Probe;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://schemas.xmlsoap.org/ws/2005/04/discovery' }

__PACKAGE__->__set_name('Probe');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    WSDiscovery10::Types::ProbeType
    WSDiscovery10::Types::ProbeMatchesType
);

}

1;


=pod

=head1 NAME

WSDiscovery10::Elements::Probe

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
Probe from the namespace http://schemas.xmlsoap.org/ws/2005/04/discovery.







=head1 METHODS

=head2 new

 my $element = WSDiscovery10::Elements::Probe->new($data);

Constructor. The following data structure may be passed to new():

 { # WSDiscovery10::Types::ProbeType
   Types => $some_value, # QNameListType
   Scopes =>  { value => $some_value },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

