package WSNotification::Types::TopicSetType;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://docs.oasis-open.org/wsn/t-1' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}


use base qw(WSNotification::Types::ExtensibleDocumented);
# Variety: sequence
use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %documentation_of :ATTR(:get<documentation>);

__PACKAGE__->_factory(
    [ qw(        documentation

    ) ],
    {
        'documentation' => \%documentation_of,
    },
    {
        'documentation' => 'WSNotification::Types::Documentation',
    },
    {

        'documentation' => 'documentation',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

WSNotification::Types::TopicSetType

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
TopicSetType from the namespace http://docs.oasis-open.org/wsn/t-1.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # WSNotification::Types::TopicSetType
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

