# ==========================================================================
#
# ZoneMinder ONVIF Control Protocol Module
# Copyright (C) Jan M. Hochstein
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# ==========================================================================

proxy:
	wsdl2perl.pl -p ONVIF::Device:: -b proxy file:wsdl/devicemgmt.wsdl
	wsdl2perl.pl -p ONVIF::Media:: -b proxy file:wsdl/media.wsdl
	wsdl2perl.pl -p ONVIF::PTZ:: -b proxy file:wsdl/ptz.wsdl
	wsdl2perl.pl -p ONVIF::Event:: -b proxy file:wsdl/event.wsdl
#	wsdl2perl.pl -p WSDiscovery:: -b proxy file:wsdl/wsdiscovery-udp.wsdl

clean:
	rm -rf proxy/*

backup:
	tar -czf ../zm-onvif.tar.gz *

install:
	/usr/bin/install -c src/onvif-probe.pl '/usr/local/bin'

