package WSDiscovery10::Types::ServiceNameType;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(0);

sub get_xmlns { 'http://schemas.xmlsoap.org/ws/2004/08/addressing' };

our $XML_ATTRIBUTE_CLASS = 'WSDiscovery10::Types::ServiceNameType::_ServiceNameType::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use base qw(
    SOAP::WSDL::XSD::Typelib::ComplexType
    SOAP::WSDL::XSD::Typelib::Builtin::QName
);

package WSDiscovery10::Types::ServiceNameType::_ServiceNameType::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %PortName_of :ATTR(:get<PortName>);

__PACKAGE__->_factory(
    [ qw(
        PortName
    ) ],
    {

        PortName => \%PortName_of,
    },
    {
        PortName => 'SOAP::WSDL::XSD::Typelib::Builtin::NCName',
    }
);

} # end BLOCK




1;


=pod

=head1 NAME

WSDiscovery10::Types::ServiceNameType

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ServiceNameType from the namespace http://schemas.xmlsoap.org/ws/2004/08/addressing.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over



=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { value => $some_value },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class WSDiscovery10::Types::ServiceNameType::_ServiceNameType::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * PortName



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::NCName|SOAP::WSDL::XSD::Typelib::Builtin::NCName>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

