package ONVIF::PTZ::Types::AudioEncoderConfigurationOptions;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Options_of :ATTR(:get<Options>);

__PACKAGE__->_factory(
    [ qw(        Options

    ) ],
    {
        'Options' => \%Options_of,
    },
    {
        'Options' => 'ONVIF::PTZ::Types::AudioEncoderConfigurationOption',
    },
    {

        'Options' => 'Options',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::PTZ::Types::AudioEncoderConfigurationOptions

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
AudioEncoderConfigurationOptions from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Options




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::PTZ::Types::AudioEncoderConfigurationOptions
   Options =>  { # ONVIF::PTZ::Types::AudioEncoderConfigurationOption
     Encoding => $some_value, # AudioEncoding
     BitrateList =>  { # ONVIF::PTZ::Types::IntList
       Items =>  $some_value, # int
     },
     SampleRateList =>  { # ONVIF::PTZ::Types::IntList
       Items =>  $some_value, # int
     },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

