package ONVIF::PTZ::Types::MotionExpressionConfiguration;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %MotionExpression_of :ATTR(:get<MotionExpression>);

__PACKAGE__->_factory(
    [ qw(        MotionExpression

    ) ],
    {
        'MotionExpression' => \%MotionExpression_of,
    },
    {
        'MotionExpression' => 'ONVIF::PTZ::Types::MotionExpression',
    },
    {

        'MotionExpression' => 'MotionExpression',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::PTZ::Types::MotionExpressionConfiguration

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
MotionExpressionConfiguration from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * MotionExpression




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::PTZ::Types::MotionExpressionConfiguration
   MotionExpression =>  { # ONVIF::PTZ::Types::MotionExpression
     Expression =>  $some_value, # string
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

