
package WSNotification::Elements::CreatePullPointResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://docs.oasis-open.org/wsn/b-2' }

__PACKAGE__->__set_name('CreatePullPointResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %PullPoint_of :ATTR(:get<PullPoint>);

__PACKAGE__->_factory(
    [ qw(        PullPoint

    ) ],
    {
        'PullPoint' => \%PullPoint_of,
    },
    {
        'PullPoint' => 'WSNotification::Types::EndpointReferenceType',
    },
    {

        'PullPoint' => 'PullPoint',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

WSNotification::Elements::CreatePullPointResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
CreatePullPointResponse from the namespace http://docs.oasis-open.org/wsn/b-2.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * PullPoint

 $element->set_PullPoint($data);
 $element->get_PullPoint();





=back


=head1 METHODS

=head2 new

 my $element = WSNotification::Elements::CreatePullPointResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   PullPoint =>  { # WSNotification::Types::EndpointReferenceType
     Address =>  { value => $some_value },
     ReferenceParameters =>  { # WSNotification::Types::ReferenceParametersType
     },
     Metadata =>  { # WSNotification::Types::MetadataType
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

