
package WSNotification::Elements::ProblemAction;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.w3.org/2005/08/addressing' }

__PACKAGE__->__set_name('ProblemAction');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();
use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    WSNotification::Types::ProblemActionType
);

}

1;


=pod

=head1 NAME

WSNotification::Elements::ProblemAction

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ProblemAction from the namespace http://www.w3.org/2005/08/addressing.







=head1 METHODS

=head2 new

 my $element = WSNotification::Elements::ProblemAction->new($data);

Constructor. The following data structure may be passed to new():

 { # WSNotification::Types::ProblemActionType
   Action =>  { value => $some_value },
   SoapAction =>  $some_value, # anyURI
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

