package ONVIF::Analytics::Types::CertificateStatus;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %CertificateID_of :ATTR(:get<CertificateID>);
my %Status_of :ATTR(:get<Status>);

__PACKAGE__->_factory(
    [ qw(        CertificateID
        Status

    ) ],
    {
        'CertificateID' => \%CertificateID_of,
        'Status' => \%Status_of,
    },
    {
        'CertificateID' => 'SOAP::WSDL::XSD::Typelib::Builtin::token',
        'Status' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    },
    {

        'CertificateID' => 'CertificateID',
        'Status' => 'Status',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::Analytics::Types::CertificateStatus

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
CertificateStatus from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * CertificateID


=item * Status




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Analytics::Types::CertificateStatus
   CertificateID =>  $some_value, # token
   Status =>  $some_value, # boolean
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

