package ONVIF::Analytics::Types::ImagingOptions20Extension2;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %IrCutFilterAutoAdjustment_of :ATTR(:get<IrCutFilterAutoAdjustment>);
my %Extension_of :ATTR(:get<Extension>);

__PACKAGE__->_factory(
    [ qw(        IrCutFilterAutoAdjustment
        Extension

    ) ],
    {
        'IrCutFilterAutoAdjustment' => \%IrCutFilterAutoAdjustment_of,
        'Extension' => \%Extension_of,
    },
    {
        'IrCutFilterAutoAdjustment' => 'ONVIF::Analytics::Types::IrCutFilterAutoAdjustmentOptions',
        'Extension' => 'ONVIF::Analytics::Types::ImagingOptions20Extension3',
    },
    {

        'IrCutFilterAutoAdjustment' => 'IrCutFilterAutoAdjustment',
        'Extension' => 'Extension',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::Analytics::Types::ImagingOptions20Extension2

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ImagingOptions20Extension2 from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * IrCutFilterAutoAdjustment


=item * Extension




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Analytics::Types::ImagingOptions20Extension2
   IrCutFilterAutoAdjustment =>  { # ONVIF::Analytics::Types::IrCutFilterAutoAdjustmentOptions
     BoundaryType =>  $some_value, # string
     BoundaryOffset =>  $some_value, # boolean
     ResponseTimeRange =>  { # ONVIF::Analytics::Types::DurationRange
       Min =>  $some_value, # duration
       Max =>  $some_value, # duration
     },
     Extension =>  { # ONVIF::Analytics::Types::IrCutFilterAutoAdjustmentOptionsExtension
     },
   },
   Extension =>  { # ONVIF::Analytics::Types::ImagingOptions20Extension3
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

