package ONVIF::Analytics::Types::MotionExpression;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS = 'ONVIF::Analytics::Types::MotionExpression::_MotionExpression::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Expression_of :ATTR(:get<Expression>);

__PACKAGE__->_factory(
    [ qw(        Expression

    ) ],
    {
        'Expression' => \%Expression_of,
    },
    {
        'Expression' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Expression' => 'Expression',
    }
);

} # end BLOCK




package ONVIF::Analytics::Types::MotionExpression::_MotionExpression::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %Type_of :ATTR(:get<Type>);

__PACKAGE__->_factory(
    [ qw(
        Type
    ) ],
    {

        Type => \%Type_of,
    },
    {
        Type => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    }
);

} # end BLOCK




1;


=pod

=head1 NAME

ONVIF::Analytics::Types::MotionExpression

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
MotionExpression from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Expression




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Analytics::Types::MotionExpression
   Expression =>  $some_value, # string
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class ONVIF::Analytics::Types::MotionExpression::_MotionExpression::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * Type



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::string|SOAP::WSDL::XSD::Typelib::Builtin::string>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

