package ONVIF::Analytics::Types::RecordingJobStateTracks;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.onvif.org/ver10/schema' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Track_of :ATTR(:get<Track>);

__PACKAGE__->_factory(
    [ qw(        Track

    ) ],
    {
        'Track' => \%Track_of,
    },
    {
        'Track' => 'ONVIF::Analytics::Types::RecordingJobStateTrack',
    },
    {

        'Track' => 'Track',
    }
);

} # end BLOCK








1;


=pod

=head1 NAME

ONVIF::Analytics::Types::RecordingJobStateTracks

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
RecordingJobStateTracks from the namespace http://www.onvif.org/ver10/schema.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Track




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # ONVIF::Analytics::Types::RecordingJobStateTracks
   Track =>  { # ONVIF::Analytics::Types::RecordingJobStateTrack
     SourceTag =>  $some_value, # string
     Destination => $some_value, # TrackReference
     Error =>  $some_value, # string
     State => $some_value, # RecordingJobState
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

