#!/bin/sh
# prerm script for zoneminder

set -e

# Source the debconf stuff
if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

# Source the dbconfig stuff
if [ /usr/share/dbconfig-common/dpkg/prerm ]; then
    . /usr/share/dbconfig-common/dpkg/prerm
    # Ask the user what do to with dbconfig when removing the package
    dbc_go zoneminder $@
fi

# #DEBHELPER#

exit 0
