
package ONVIF::Device::Elements::CreateUsers;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('CreateUsers');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %User_of :ATTR(:get<User>);

__PACKAGE__->_factory(
    [ qw(        User

    ) ],
    {
        'User' => \%User_of,
    },
    {
        'User' => 'ONVIF::Device::Types::User',
    },
    {

        'User' => 'User',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::CreateUsers

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
CreateUsers from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * User

 $element->set_User($data);
 $element->get_User();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::CreateUsers->new($data);

Constructor. The following data structure may be passed to new():

 {
   User =>  { # ONVIF::Device::Types::User
     Username =>  $some_value, # string
     Password =>  $some_value, # string
     UserLevel => $some_value, # UserLevel
     Extension =>  { # ONVIF::Device::Types::UserExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

