
package ONVIF::Device::Elements::GetCertificateInformationResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetCertificateInformationResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %CertificateInformation_of :ATTR(:get<CertificateInformation>);

__PACKAGE__->_factory(
    [ qw(        CertificateInformation

    ) ],
    {
        'CertificateInformation' => \%CertificateInformation_of,
    },
    {
        'CertificateInformation' => 'ONVIF::Device::Types::CertificateInformation',
    },
    {

        'CertificateInformation' => 'CertificateInformation',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetCertificateInformationResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetCertificateInformationResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * CertificateInformation

 $element->set_CertificateInformation($data);
 $element->get_CertificateInformation();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetCertificateInformationResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   CertificateInformation =>  { # ONVIF::Device::Types::CertificateInformation
     CertificateID =>  $some_value, # token
     IssuerDN =>  $some_value, # string
     SubjectDN =>  $some_value, # string
     KeyUsage =>  { value => $some_value },
     ExtendedKeyUsage =>  { value => $some_value },
     KeyLength =>  $some_value, # int
     Version =>  $some_value, # string
     SerialNum =>  $some_value, # string
     SignatureAlgorithm =>  $some_value, # string
     Validity =>  { # ONVIF::Device::Types::DateTimeRange
       From =>  $some_value, # dateTime
       Until =>  $some_value, # dateTime
     },
     Extension =>  { # ONVIF::Device::Types::CertificateInformationExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

