
package ONVIF::Device::Elements::GetDynamicDNSResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetDynamicDNSResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DynamicDNSInformation_of :ATTR(:get<DynamicDNSInformation>);

__PACKAGE__->_factory(
    [ qw(        DynamicDNSInformation

    ) ],
    {
        'DynamicDNSInformation' => \%DynamicDNSInformation_of,
    },
    {
        'DynamicDNSInformation' => 'ONVIF::Device::Types::DynamicDNSInformation',
    },
    {

        'DynamicDNSInformation' => 'DynamicDNSInformation',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetDynamicDNSResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetDynamicDNSResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DynamicDNSInformation

 $element->set_DynamicDNSInformation($data);
 $element->get_DynamicDNSInformation();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetDynamicDNSResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   DynamicDNSInformation =>  { # ONVIF::Device::Types::DynamicDNSInformation
     Type => $some_value, # DynamicDNSType
     Name => $some_value, # DNSName
     TTL =>  $some_value, # duration
     Extension =>  { # ONVIF::Device::Types::DynamicDNSInformationExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

