
package ONVIF::Device::Elements::GetHostnameResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetHostnameResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %HostnameInformation_of :ATTR(:get<HostnameInformation>);

__PACKAGE__->_factory(
    [ qw(        HostnameInformation

    ) ],
    {
        'HostnameInformation' => \%HostnameInformation_of,
    },
    {
        'HostnameInformation' => 'ONVIF::Device::Types::HostnameInformation',
    },
    {

        'HostnameInformation' => 'HostnameInformation',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetHostnameResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetHostnameResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * HostnameInformation

 $element->set_HostnameInformation($data);
 $element->get_HostnameInformation();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetHostnameResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   HostnameInformation =>  { # ONVIF::Device::Types::HostnameInformation
     FromDHCP =>  $some_value, # boolean
     Name =>  $some_value, # token
     Extension =>  { # ONVIF::Device::Types::HostnameInformationExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

