
package ONVIF::Device::Elements::GetServicesResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetServicesResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Service_of :ATTR(:get<Service>);

__PACKAGE__->_factory(
    [ qw(        Service

    ) ],
    {
        'Service' => \%Service_of,
    },
    {
        'Service' => 'ONVIF::Device::Types::Service',
    },
    {

        'Service' => 'Service',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetServicesResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetServicesResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Service

 $element->set_Service($data);
 $element->get_Service();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetServicesResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   Service =>  { # ONVIF::Device::Types::Service
     Namespace =>  $some_value, # anyURI
     XAddr =>  $some_value, # anyURI
     Capabilities =>  {
     },
     Version =>  { # ONVIF::Device::Types::OnvifVersion
       Major =>  $some_value, # int
       Minor =>  $some_value, # int
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

