
package ONVIF::Device::Elements::GetSystemSupportInformationResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetSystemSupportInformationResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %SupportInformation_of :ATTR(:get<SupportInformation>);

__PACKAGE__->_factory(
    [ qw(        SupportInformation

    ) ],
    {
        'SupportInformation' => \%SupportInformation_of,
    },
    {
        'SupportInformation' => 'ONVIF::Device::Types::SupportInformation',
    },
    {

        'SupportInformation' => 'SupportInformation',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetSystemSupportInformationResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetSystemSupportInformationResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * SupportInformation

 $element->set_SupportInformation($data);
 $element->get_SupportInformation();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetSystemSupportInformationResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   SupportInformation =>  { # ONVIF::Device::Types::SupportInformation
     Binary =>  { # ONVIF::Device::Types::AttachmentData
       Include =>  { # ONVIF::Device::Types::Include
       },
     },
     String =>  $some_value, # string
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

