
package ONVIF::Device::Elements::GetZeroConfigurationResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('GetZeroConfigurationResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %ZeroConfiguration_of :ATTR(:get<ZeroConfiguration>);

__PACKAGE__->_factory(
    [ qw(        ZeroConfiguration

    ) ],
    {
        'ZeroConfiguration' => \%ZeroConfiguration_of,
    },
    {
        'ZeroConfiguration' => 'ONVIF::Device::Types::NetworkZeroConfiguration',
    },
    {

        'ZeroConfiguration' => 'ZeroConfiguration',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::GetZeroConfigurationResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
GetZeroConfigurationResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * ZeroConfiguration

 $element->set_ZeroConfiguration($data);
 $element->get_ZeroConfiguration();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::GetZeroConfigurationResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   ZeroConfiguration =>  { # ONVIF::Device::Types::NetworkZeroConfiguration
     InterfaceToken => $some_value, # ReferenceToken
     Enabled =>  $some_value, # boolean
     Addresses => $some_value, # IPv4Address
     Extension =>  { # ONVIF::Device::Types::NetworkZeroConfigurationExtension
       Extension =>  { # ONVIF::Device::Types::NetworkZeroConfigurationExtension2
       },
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

