
package ONVIF::Device::Elements::ScanAvailableDot11NetworksResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('ScanAvailableDot11NetworksResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Networks_of :ATTR(:get<Networks>);

__PACKAGE__->_factory(
    [ qw(        Networks

    ) ],
    {
        'Networks' => \%Networks_of,
    },
    {
        'Networks' => 'ONVIF::Device::Types::Dot11AvailableNetworks',
    },
    {

        'Networks' => 'Networks',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::ScanAvailableDot11NetworksResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
ScanAvailableDot11NetworksResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Networks

 $element->set_Networks($data);
 $element->get_Networks();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::ScanAvailableDot11NetworksResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   Networks =>  { # ONVIF::Device::Types::Dot11AvailableNetworks
     SSID => $some_value, # Dot11SSIDType
     BSSID =>  $some_value, # string
     AuthAndMangementSuite => $some_value, # Dot11AuthAndMangementSuite
     PairCipher => $some_value, # Dot11Cipher
     GroupCipher => $some_value, # Dot11Cipher
     SignalStrength => $some_value, # Dot11SignalStrength
     Extension =>  { # ONVIF::Device::Types::Dot11AvailableNetworksExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

