
package ONVIF::Device::Elements::SendAuxiliaryCommandResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('SendAuxiliaryCommandResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %AuxiliaryCommandResponse_of :ATTR(:get<AuxiliaryCommandResponse>);

__PACKAGE__->_factory(
    [ qw(        AuxiliaryCommandResponse

    ) ],
    {
        'AuxiliaryCommandResponse' => \%AuxiliaryCommandResponse_of,
    },
    {
        'AuxiliaryCommandResponse' => 'ONVIF::Device::Types::AuxiliaryData',
    },
    {

        'AuxiliaryCommandResponse' => 'AuxiliaryCommandResponse',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::SendAuxiliaryCommandResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SendAuxiliaryCommandResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * AuxiliaryCommandResponse

 $element->set_AuxiliaryCommandResponse($data);
 $element->get_AuxiliaryCommandResponse();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::SendAuxiliaryCommandResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   AuxiliaryCommandResponse => $some_value, # AuxiliaryData
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

