
package ONVIF::Device::Elements::SetDiscoveryMode;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('SetDiscoveryMode');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %DiscoveryMode_of :ATTR(:get<DiscoveryMode>);

__PACKAGE__->_factory(
    [ qw(        DiscoveryMode

    ) ],
    {
        'DiscoveryMode' => \%DiscoveryMode_of,
    },
    {
        'DiscoveryMode' => 'ONVIF::Device::Types::DiscoveryMode',
    },
    {

        'DiscoveryMode' => 'DiscoveryMode',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::SetDiscoveryMode

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SetDiscoveryMode from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * DiscoveryMode

 $element->set_DiscoveryMode($data);
 $element->get_DiscoveryMode();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::SetDiscoveryMode->new($data);

Constructor. The following data structure may be passed to new():

 {
   DiscoveryMode => $some_value, # DiscoveryMode
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

