
package ONVIF::Device::Elements::SetHostnameFromDHCPResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('SetHostnameFromDHCPResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %RebootNeeded_of :ATTR(:get<RebootNeeded>);

__PACKAGE__->_factory(
    [ qw(        RebootNeeded

    ) ],
    {
        'RebootNeeded' => \%RebootNeeded_of,
    },
    {
        'RebootNeeded' => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    },
    {

        'RebootNeeded' => 'RebootNeeded',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::SetHostnameFromDHCPResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SetHostnameFromDHCPResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * RebootNeeded

 $element->set_RebootNeeded($data);
 $element->get_RebootNeeded();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::SetHostnameFromDHCPResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   RebootNeeded =>  $some_value, # boolean
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

