
package ONVIF::Device::Elements::SetHostname;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('SetHostname');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Name_of :ATTR(:get<Name>);

__PACKAGE__->_factory(
    [ qw(        Name

    ) ],
    {
        'Name' => \%Name_of,
    },
    {
        'Name' => 'SOAP::WSDL::XSD::Typelib::Builtin::token',
    },
    {

        'Name' => 'Name',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::SetHostname

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SetHostname from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Name

 $element->set_Name($data);
 $element->get_Name();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::SetHostname->new($data);

Constructor. The following data structure may be passed to new():

 {
   Name =>  $some_value, # token
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

