
package ONVIF::Device::Elements::SetNetworkProtocols;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('SetNetworkProtocols');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %NetworkProtocols_of :ATTR(:get<NetworkProtocols>);

__PACKAGE__->_factory(
    [ qw(        NetworkProtocols

    ) ],
    {
        'NetworkProtocols' => \%NetworkProtocols_of,
    },
    {
        'NetworkProtocols' => 'ONVIF::Device::Types::NetworkProtocol',
    },
    {

        'NetworkProtocols' => 'NetworkProtocols',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::SetNetworkProtocols

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
SetNetworkProtocols from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * NetworkProtocols

 $element->set_NetworkProtocols($data);
 $element->get_NetworkProtocols();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::SetNetworkProtocols->new($data);

Constructor. The following data structure may be passed to new():

 {
   NetworkProtocols =>  { # ONVIF::Device::Types::NetworkProtocol
     Name => $some_value, # NetworkProtocolType
     Enabled =>  $some_value, # boolean
     Port =>  $some_value, # int
     Extension =>  { # ONVIF::Device::Types::NetworkProtocolExtension
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

