
package ONVIF::Device::Elements::UpgradeSystemFirmwareResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.onvif.org/ver10/device/wsdl' }

__PACKAGE__->__set_name('UpgradeSystemFirmwareResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %Message_of :ATTR(:get<Message>);

__PACKAGE__->_factory(
    [ qw(        Message

    ) ],
    {
        'Message' => \%Message_of,
    },
    {
        'Message' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'Message' => 'Message',
    }
);

} # end BLOCK







} # end of BLOCK



1;


=pod

=head1 NAME

ONVIF::Device::Elements::UpgradeSystemFirmwareResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
UpgradeSystemFirmwareResponse from the namespace http://www.onvif.org/ver10/device/wsdl.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * Message

 $element->set_Message($data);
 $element->get_Message();





=back


=head1 METHODS

=head2 new

 my $element = ONVIF::Device::Elements::UpgradeSystemFirmwareResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   Message =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

