name: CI Fedora 36

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        crypto_backend: [ gnutls, openssl ]
        jwt_backend: [ libjwt, jwt_cpp ]
        exclude:
          - crypto_backend: gnutls
            jwt_backend: jwt_cpp
          - crypto_backend: gnutls
            jwt_backend: libjwt
    runs-on: ubuntu-latest
    container: fedora:36

    steps:
      - name: Install git
        run: yum -y install git
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
            yum -y update && yum -y upgrade
            yum install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
            yum -y groupinstall "Development Tools"
            yum -y install make cmake g++
            yum -y install libavutil-free libavutil-free-devel libavcodec-free libavcodec-free-devel libavformat-free libavformat-free-devel libswresample-free libswresample-free-devel
            yum -y install libswscale-free libswscale-free-devel libavdevice-free libavdevice-free-devel libvncserver libvncserver-devel libcurl libcurl-devel
            yum -y install libvncserver libvncserver-devel openssl-devel openssl-libs libjwt libjwt-devel libjpeg-turbo libjpeg-turbo-deve
            yum -y install polkit polkit-devel polkit-libs
            yum -y install perl-Date-Manip perl-DBD-MySQL perl-Sys-Mmap perl-libwww-perl perl-Sys-Syslog perl-Time-HiRes perl-ExtUtils-Depends perl-ExtUtils-MakeMaker
            yum -y install vlc-devel postgresql postgresql-server mariadb-devel
            yum -y install postgresql postgresql-server mariadb-devel
      - name: Prepare
        run: mkdir build
      - name: Configure
        run: cd build && cmake --version && cmake .. -DBUILD_MAN=0 -DBUILD_TEST_SUITE=1 -DENABLE_WERROR=1  -DZM_CRYPTO_BACKEND=${{ matrix.crypto_backend }} -DZM_JWT_BACKEND=${{ matrix.jwt_backend }}
      - name: Build
        run: cd build && make -j3 | grep --line-buffered -Ev '^(cp lib\/|Installing.+\.pm)' && (exit ${PIPESTATUS[0]})
      - name: Run tests
        run: cd build/tests && ./tests "~[notCI]"
