<?php
// Tests web/includes/Network.php authNetworkPrefix(): IPv4 is masked to /24,
// IPv6 to /64, and the lowercase-hex output is byte-for-byte identical to the
// C++ AuthNetworkPrefix() (tests/zm_utils.cpp) so a hash generated by one side
// validates on the other.
//
// Run as: php tests/php/test_auth_network_prefix.php

require_once __DIR__.'/../../web/includes/Network.php';

$failures = 0;
$passes = 0;

function check($name, $got, $expected) {
  global $failures, $passes;
  if ($got === $expected) {
    $passes++;
    echo "ok - $name\n";
  } else {
    $failures++;
    echo "not ok - $name (got '".var_export($got, true)."' expected '".var_export($expected, true)."')\n";
  }
}

// Empty / non-IP passthrough
check('empty returns empty', authNetworkPrefix(''), '');
check('null returns empty', authNetworkPrefix(null), '');
check('non-ip verbatim', authNetworkPrefix('not-an-ip'), 'not-an-ip');

// IPv4 -> /24 (must match the C++ Catch2 expectations exactly)
check('ipv4 /24 hex', authNetworkPrefix('192.168.1.55'), 'c0a80100');
check('ipv4 same /24 collapses',
  authNetworkPrefix('192.168.1.99'), authNetworkPrefix('192.168.1.55'));
check('ipv4 different /24 differs',
  authNetworkPrefix('192.168.2.55') !== authNetworkPrefix('192.168.1.55'), true);

// IPv6 -> /64
check('ipv6 /64 hex',
  authNetworkPrefix('2001:db8:1:2::abcd'), '20010db8000100020000000000000000');
check('ipv6 same /64 collapses (privacy rotation)',
  authNetworkPrefix('2001:db8:1:2:ffff:ffff:ffff:ffff'), authNetworkPrefix('2001:db8:1:2::1'));
check('ipv6 different /64 differs',
  authNetworkPrefix('2001:db8:1:3::1') !== authNetworkPrefix('2001:db8:1:2::1'), true);

echo "\n$passes passed, $failures failed\n";
exit($failures ? 1 : 0);
?>
